### PR TITLE
Plasma 6 support & configurable "No artist" prompt

### PR DESCRIPTION
**Pull request by chiyuki0325**

### CODE REVIEW

**Comment by JunoNgx** [comment]
@chiyuki0325 Thank you for your contribution.

As a matter of fact, I'm no longer using KDE Plasma, and as such, I'm no longer in a good position to continuously maintain this project. Is there any interest from your side to take over this?

**Comment by chiyuki0325** [comment]
Currently I'm using Plasma 6 and this widget fits my panel configuration perfectly.  Although I don't know how to write a widget well, I am obviously glad to take it over 😉

**Comment by JunoNgx** [comment]
Thank you for taking over.

I have sent you an invitation as a collaborator for this repository. In the meantime, please feel free to package this and publish your own version on the KDE store so other people may download and use it.

I'll find time to add note that my published version has been deprecated.

**Comment by warcayac** [comment]
> Currently I'm using Plasma 6 and this widget fits my panel configuration perfectly. Although I don't know how to write a widget well, I am obviously glad to take it over 😉

@chiyuki0325, What plans do you have for this Widget? Will you soon publish this Widget for Plasma 6? If not, then can you give me the steps on how to compile the source in EndeavorOS with the changes ready for Plasma 6? Thank you

**Comment by JunoNgx** [comment]
@warcayac No compilation is needed. You just need to put the source in your widget directory. This is all included in the [Plasma documentation](https://develop.kde.org/docs/plasma/widget/).

**Pull request merged**
